Algoritmo "CalcularParOuImpar"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 5/29/2024
Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite o número: ")
leia(numero)



se (numero % 2 > 0) entao
   escreva("O número é impar")
senao
   escreva("O número é par")
fimse

Fimalgoritmo